### ISSUE TITLE
loading error

### ISSUE THREAD

**Issue by georgedendle** [Bizzi-Body/HowToDisplayImagesInTableViewFromParse#1] opened 2015-03-01 17:31 UTC
it works fine with your client id but when i edited it to have my things in it just takes ages to load and when it loads nothing happens.
 
find code here http://stackoverflow.com/questions/28793705/parse-com-query-not-loading

**Comment by Bizzi-Body** [comment] 2015-03-02 12:12
Hi George.  I have posted a fix over on the blog site - http://blog.bizzi-body.com/2015/02/13/how-to-display-parse-com-images-in-a-table-view/.  I believe the issue is that the custom cell class defined in your swift file has a different name to the custom cell defined in the story board.  Please confirm so that I can close this issue.

**Closed** 2015-03-10 13:50 UTC
